chore: added eslint rules
- fixed: github desktop commit and push errors

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,10 +1,12 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
-echo "Running lint check..."
-npm run lint
-if [ $? -ne 0 ]; then
-    echo "Linting failed. Commit aborted."
-    exit 1
-fi
-echo "Linting passed. Proceeding with commit."
+node .husky/pre-commit.js
+
+# echo "Running lint check..."
+# npx lint-staged
+# if [ $? -ne 0 ]; then
+#     echo "Linting failed. Commit aborted."
+#     exit 1
+# fi
+# echo "Linting passed. Proceeding with commit."
